import Footer from "./components/common/footer/footer";
import Navbar from "./components/common/navbar/navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="bg-bgSlate">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
