export const usersListData = [
  {
    id: 1,
    name: "Person 1",
    category: "Web Developer",
    number: 7256308880,
    email: "person1@email.com",
  },
  {
    id: 2,
    name: "Person 2",
    category: "Web Developer",
    number: 6442751933,
    email: "person2@email.com",
  },
  {
    id: 3,
    name: "Person 3",
    category: "Andriod Developer",
    number: 9528289395,
    email: "person3@email.com",
  },
  {
    id: 4,
    name: "Person 4",
    category: "Web Developer",
    number: 9529359870,
    email: "person4@email.com",
  },
  {
    id: 5,
    name: "Person 5",
    category: "Web Developer",
    number: 2858065111,
    email: "person5@email.com",
  },
  {
    id: 6,
    name: "Person 6",
    category: "Andriod Developer",
    number: 7158766473,
    email: "person6@email.com",
  },
  {
    id: 7,
    name: "Person 7",
    category: "Web Developer",
    number: 1251099409,
    email: "person7@email.com",
  },
  {
    id: 8,
    name: "Person 8",
    category: "Web Developer",
    number: 9321583797,
    email: "person8@email.com",
  },
  {
    id: 9,
    name: "Person 9",
    category: "Andriod Developer",
    number: 6368327027,
    email: "person9@email.com",
  },
  {
    id: 10,
    name: "Person 10",
    category: "Andriod Developer",
    number: 9377898743,
    email: "person10@email.com",
  },
];
